name: Run Weather Pipeline

on:
  schedule:
    - cron: '26 05 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: 'latest'

      - name: Install dependencies
        run: uv sync

      - name: Run Weather Pipeline
        env:
          LATITUDE: ${{ vars.LATITUDE }}
          LONGITUDE: ${{ vars.LONGITUDE }}
          LOCATION_NAME: ${{ vars.LOCATION_NAME }}
          TEMP_MAX_THRESHOLD: ${{ vars.TEMP_MAX_THRESHOLD }}
          UV_THRESHOLD: ${{ vars.UV_THRESHOLD }}
          PRECIPITATION_THRESHOLD: ${{ vars.PRECIPITATION_THRESHOLD }}
          
          ALERT_ENABLED: true
          PUSH_NOTIFICATION_ENABLED: true
          PUSH_NOTIFICATION_TOPIC: ${{ vars.PUSH_NOTIFICATION_TOPIC }}
          EMAIL_ENABLED: false
          #GMAIL_SMTP_APP_PASSWORD: ${{ secrets.GMAIL_SMTP_APP_PASSWORD }}
          #SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          #DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: uv run python src/main.py

      - name: Upload processed data
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pipeline-data-${{ github.run_number }}
          path: weather_notification/data/processed/*.parquet
          retention-days: 7
          if-no-files-found: ignore
